"""empty message

Revision ID: 25b2bd335154
Revises: bf0443a07abe
Create Date: 2022-02-18 15:52:19.506476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b2bd335154'
down_revision = 'bf0443a07abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('cart', sa.Column('cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'cost')
    op.drop_column('cart', 'quantity')
    # ### end Alembic commands ###
