"""empty message

Revision ID: 601ca59c9778
Revises: 4c3554804bee
Create Date: 2022-02-19 11:21:11.519386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601ca59c9778'
down_revision = '4c3554804bee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('category', sa.String(), nullable=True))
    op.add_column('user', sa.Column('gold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gold')
    op.drop_column('item', 'category')
    # ### end Alembic commands ###
