"""empty message

Revision ID: b5c758586fb8
Revises: 25b2bd335154
Create Date: 2022-02-18 16:00:20.760873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c758586fb8'
down_revision = '25b2bd335154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'cost')
    op.drop_column('cart', 'quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cart', sa.Column('cost', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
