"""empty message

Revision ID: bf0443a07abe
Revises: ec187492a2f2
Create Date: 2022-02-16 21:56:09.562001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0443a07abe'
down_revision = 'ec187492a2f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('img', sa.String(), nullable=True))
    op.add_column('item', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_item_created_on'), 'item', ['created_on'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_created_on'), table_name='item')
    op.drop_column('item', 'created_on')
    op.drop_column('item', 'img')
    # ### end Alembic commands ###
